In [1]:
!pip install transformers datasets -q
!pip install pymongo -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 26.0 MB/s eta 0:00:00

In [7]:
import pandas as pd
from pymongo import MongoClient
from google.colab import userdata

#uri = userdata.get('MGDB_IAI') #到時候把老師的mongoDB key放進colab旁邊的secrets
url="mongodb+srv://ici:ici2010@cluster0.uhtx50m.mongodb.net/"
client = MongoClient(url)

db = client["Group8"]

data1 = db["labeled_training_data"]
data2= db["漢字與詞語"]

cursor1 = data1.find()
cursor2 = data2.find()

trained_data = pd.DataFrame(list(cursor1))
rubric_data = pd.DataFrame(list(cursor2))

In [8]:
trained_data

,_id,text_segment,calculated_level,source
0,6a12bdc0d14be1651570cf7b,這個小小的第三者，似乎一生下來就得到父母的鍾愛，在她噘著小嘴唇甜蜜睡覺的時候，在她睜開烏黑的...,2,文本
1,6a12bdc0d14be1651570cf7c,我們的臥室開始有釘鎚的響聲，鐵絲安裝起來了，一道，兩道，三道，四道，五道，六道。她的尿布像一...,2,文本
2,6a12bdc0d14be1651570cf7d,兩部車子回家的公務員生活樂趣被破壞了，但是我們卻從另一方面得到了補償。我們可以捏捏嬰兒的小手...,2,文本
3,6a12bdc0d14be1651570cf7e,我們享受她給我們的一切聲音，這聲音使我們的房間格外溫暖。我們偷看她安靜時候臉上的表情，這表情...,2,文本
4,6a12bdc0d14be1651570cf7f,小太陽不怕天上雲朵的遮掩，小太陽能透過雨絲，透過尿布的迷魂陣，透過愁苦靈魂堅硬的外殻，暖烘烘...,2,文本
...,...,...,...,...
317,6a12bdc2d14be1651570d0b8,【楊喚詩集】我是忙碌的 楊喚 我是忙碌的。 我是忙碌的。 我忙於搖醒火把， 我忙於雕塑自己；...,3,詩集
318,6a12bdc2d14be1651570d0b9,我是忙碌的。 我是忙碌的。,2,詩集
319,6a12bdc2d14be1651570d0ba,【楊喚詩集】童詩：小蜘蛛 楊喚 要黏住小蚊子討厭的尖嘴巴。 要黏住小蒼蠅亂飛的小翅膀。 蜜蜂...,2,詩集
320,6a12bdc2d14be1651570d0bb,【楊喚詩集】小時候 楊喚 小時候， 在哭聲裡長大， 讓我的日子永遠蒼白憂鬱。 從落後的鄉村走...,2,詩集
321,6a12bdc2d14be1651570d0bc,【楊喚詩集】童詩：下雨了 楊喚 下雨了。 太陽怕淋雨回家去休假。 火車怕淋雨忙著開向車站。 ...,2,詩集

In [9]:
rubric_data

                            _id   漢字  級別
0      6a12bdb7d14be165157089a1    的   1
1      6a12bdb7d14be165157089a2    是   1
2      6a12bdb7d14be165157089a3    一   1
3      6a12bdb7d14be165157089a4    個   1
4      6a12bdb7d14be165157089a5    我   1
...                         ...  ...  ..
17877  6a12bdb7d14be1651570cf76   作物   7
17878  6a12bdb7d14be1651570cf77  座右銘   7
17879  6a12bdb7d14be1651570cf78   坐鎮   7
17880  6a12bdb7d14be1651570cf79   坐姿   7
17881  6a12bdb7d14be1651570cf7a   做作   7

[17882 rows x 3 columns]